AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude: ["**/*_spec.rb"]

Lint/ConstantDefinitionInBlock:
  Exclude: ["**/*_spec.rb"]
