AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude: ["**/*_spec.rb"]

Metrics/BlockLength:
  Exclude: ["**/*_spec.rb"]

Lint/ConstantDefinitionInBlock:
  Exclude: ["**/*_spec.rb"]
