version: "3.9"

services:
  rover_app:
    build: ./build
    container_name: rover_app
    restart: always
    tty: true
    command: bash /entrypoint.sh
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1.5
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ../:/app
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - rover_app

networks:
  rover_app:
